<Project Sdk="Microsoft.NET.Sdk.Web">
    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <InvariantGlobalization>true</InvariantGlobalization>
        <EnableConfigurationBindingGenerator>true</EnableConfigurationBindingGenerator>
        <InterceptorsPreviewNamespaces>$(InterceptorsPreviewNamespaces);Dapper.AOT</InterceptorsPreviewNamespaces>
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    </PropertyGroup>


    <ItemGroup>
        <EmbeddedResource Include="Database\Migrations\Script0001_Init.sql" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="MessagePipe" Version="1.8.1" />
      <PackageReference Include="MessagePipe.Analyzer" Version="1.8.1">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="Microsoft.Extensions.FileSystemGlobbing" Version="9.0.6" />
      <PackageReference Include="Dapper" Version="2.1.66" />
      <PackageReference Include="Dapper.AOT" Version="1.0.48" />
      <PackageReference Include="Microsoft.Data.Sqlite" Version="9.0.8" />
      <PackageReference Include="Microsoft.Extensions.Http.Polly" Version="9.0.8" />
    </ItemGroup>
</Project>
