// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SS14.Labeller.Database;

#nullable disable

namespace SS14.Labeller.Database.Migrations
{
    [DbContext(typeof(CustomDbContext))]
    partial class CustomDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SS14.Labeller.Database.Entities.DiscourseTopicEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("IssueNumber")
                        .HasColumnType("integer")
                        .HasColumnName("issue_number");

                    b.Property<string>("RepoName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("repo_name");

                    b.Property<string>("RepoOwner")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("repo_owner");

                    b.Property<int>("TopicId")
                        .HasColumnType("integer")
                        .HasColumnName("topic_id");

                    b.HasKey("Id")
                        .HasName("pk_discussions");

                    b.HasIndex("IssueNumber")
                        .HasDatabaseName("ix_discussions_issue_number");

                    b.HasIndex("RepoName")
                        .HasDatabaseName("ix_discussions_repo_name");

                    b.HasIndex("RepoOwner")
                        .HasDatabaseName("ix_discussions_repo_owner");

                    b.ToTable("discussions", "discourse");
                });
#pragma warning restore 612, 618
        }
    }
}
